### ISSUE TITLE
Export of Custom Rules Fails in 4.7.1

### ISSUE THREAD

**Issue by tdmomega77** [fireeye/HXTool#116]
I am using HXTool 4.7.1, and attempts to export custom configured rules are failing.  My on-prem HX appliances are running the latest 5.3.0 OS, and I am using a Python 3.7X version to run HXTool on a Windows 10 Enterprise 21H2 OS. A snippet of the hxtool.log shows the following when attempts to export are made:

_[2022-11-17 14:33:26,604] {app} {Thread-741} ERROR - Exception on /api/v1/indicators/export [POST]
Traceback (most recent call last):
  File "C:\Temp\hxtool_4.7.1_standalone\Python37-32\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Temp\hxtool_4.7.1_standalone\Python37-32\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Temp\hxtool_4.7.1_standalone\Python37-32\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Temp\hxtool_4.7.1_standalone\Python37-32\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Temp\hxtool_4.7.1_standalone\hxtool_util.py", line 58, in is_session_valid
    ret = f(*args, **kwargs)
  File "C:\Temp\hxtool_4.7.1_standalone\hxtool_api.py", line 1349, in hxtool_api_indicators_export
    return send_file(buffer, attachment_filename=iocfname, as_attachment=True)
TypeError: send_file() got an unexpected keyword argument 'attachment_filename'_

Is this a known bug, or could this be something on my side?  My current Python modules and versions installed are:

certifi==2022.9.24
chardet==5.0.0
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
Cython==0.29.32
Flask==2.2.2
idna==3.4
importlib-metadata==5.0.0
itsdangerous==2.1.2
jaraco.classes==3.2.3
Jinja2==3.1.2
keyring==23.11.0
MarkupSafe==2.1.1
more-itertools==9.0.0
numpy==1.21.6
pandas==0.25.1
pickle5==0.0.12
pycryptodome==3.15.0
pycryptodomex==3.15.0
python-dateutil==2.8.2
pytz==2022.6
pywin32-ctypes==0.2.0
requests==2.28.1
six==1.16.0
tinydb==4.7.0
typing_extensions==4.4.0
urllib3==1.26.12
Werkzeug==2.2.2
zipp==3.10.0

**Comment by tdmomega77** [comment]
Nevermind...my updated Flask module replaced 'attachment_filename' with 'download_name' per https://github.com/pallets/flask/issues/4753.  Once I updated these entries in hxtool_api.py, I was able to download custom rules again.
