### ISSUE TITLE
Internal Server Error after Stock  Setup

### ISSUE THREAD

**Issue by senapetschnig** [fireeye/HXTool#123]
Hi, 
i installed HX Tool and all the Requirements, it starts up without errors.
But on the first request i get a internal server error (http 500).
Only config changes in (data/config.json)
    "network": {
                "ssl": "enabled",
                "port": 443,
                "listen_address": "0.0.0.0",
                "session_timeout": 30
I left the rest, exactly the same as it was.

Any help would be appreciated, because the documentation isn't suggesting any more settings.
Thanks in advanced

Stack Trace:
[2023-04-28 11:26:44,233] {app} {Thread-12} ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2189, in wsgi_app
    ctx.push()
  File "/usr/local/lib/python3.9/dist-packages/flask/ctx.py", line 377, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/srv/HXTool-4.7.1/hxtool_session.py", line 68, in open_session
    session_id = request.cookies.get(app.session_cookie_name)
AttributeError: 'Flask' object has no attribute 'session_cookie_name'
[2023-04-28 11:26:44,234] {app} {Thread-12} ERROR - Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2189, in wsgi_app
    ctx.push()
  File "/usr/local/lib/python3.9/dist-packages/flask/ctx.py", line 377, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/srv/HXTool-4.7.1/hxtool_session.py", line 68, in open_session
    session_id = request.cookies.get(app.session_cookie_name)
AttributeError: 'Flask' object has no attribute 'session_cookie_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1508, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2005, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/srv/HXTool-4.7.1/hxtool_session.py", line 86, in save_session
    if not session.new:
AttributeError: 'NoneType' object has no attribute 'new'

**Comment by senapetschnig** [comment]
Thanks,
it would be good to have this Information in the documentation.
I found a other workaround.
not pretty but working.
adding 
app.session_cookie_name = "session_cookie_name"
in the hxtool.py also does the job with flask versions higher than 2.2

Regards
    Sebastian
