### ISSUE TITLE
Cannot edit custom rules (Internal Server Error) | UnboundLocalError

### ISSUE THREAD

**Issue by robertriskin** [fireeye/HXTool#125]
Hi,

I haven't updated our custom rules in a while and was using 4.5 successfully for this. I tried to edit one of our custom rules (that is and has been working for years) and on the web interface we receive "Internal Server Error" and on commandline we receive this error:

[2023-07-24 08:27:29,858] {app} {Thread-60} ERROR - Exception on /rtioc [GET]
Traceback (most recent call last):
  File "C:\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\hxtool-4.8\hxtool_util.py", line 58, in is_session_valid
    ret = f(*args, **kwargs)
  File ".\hxtool.py", line 329, in rtioc
    iocname=iocname,
UnboundLocalError: local variable 'iocname' referenced before assignment

I then upgraded to hxtool 4.8-pre and still receive the same exact error so i imagine something on the appliance api changed as this worked fine in 4.5. We are using python 3.8.3 if that helps. 

Additionally we cannot seem to view any of the rules as well we receive the following when clicking view on custom and fireeye builtin rules:

"{\"api_success\": false, \"api_response_code\": 403, \"api_response\": \"{\\\"presence\\\": {\\\"details\\\": [{\\\"type\\\": \\\"error\\\", \\\"code\\\": 1101, \\\"message\\\": \\\"User action in unrestricted indicator category is not permitted with the current user's role.\\\"}], \\\"route\\\": \\\"/hx/api/v3/indicators/category/indicator/conditions/type\\\", \\\"message\\\": \\\"Forbidden\\\"}, \\\"execution\\\": {\\\"details\\\": [{\\\"type\\\": \\\"error\\\", \\\"code\\\": 1101, \\\"message\\\": \\\"User action in unrestricted indicator category is not permitted with the current user's role.\\\"}], \\\"route\\\": \\\"/hx/api/v3/indicators/category/indicator/conditions/type\\\", \\\"message\\\": \\\"Forbidden\\\"}}\"}"

Any help would be greatly appreciated!

**Comment by robertriskin** [comment]
Please disregard my issue - the issue was right there in front of me. I used a non-api admin role to login. I logged in using a api_admin role and all is well! Thank you and sorry for the false flag!
