### ISSUE TITLE
true should be True

### ISSUE THREAD

**Issue by bridgeythegeek** [fireeye/HXTool#72]
`true` has been used as a constant when it should probably be `True`... depending on what happens later.

https://github.com/fireeye/HXTool/blob/4db2f4412eeff16681308713fab5b067c548222b/hxtool_api.py#L1657
https://github.com/fireeye/HXTool/blob/4db2f4412eeff16681308713fab5b067c548222b/hxtool_api.py#L1660
https://github.com/fireeye/HXTool/blob/4db2f4412eeff16681308713fab5b067c548222b/hxtool_api.py#L1663

Regardless, `true` is throwing `NameError`...

```
[2021-04-01 08:05:42,856] {app} {Thread-224} ERROR - Exception on /api/v1/acquisition/multi/file_listing/new [POST]
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/.pyenv/versions/3.7.3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/Code/HXTool-master/hxtool_util.py", line 52, in is_session_valid
    ret = f(*args, **kwargs)
  File "/Users/user/Code/HXTool-master/hxtool_api.py", line 1657, in hxtool_api_acquisition_multi_file_listing
    'value' : true
NameError: name 'true' is not defined
```

**Comment by B0fH** [comment]
Fixed in #73
