### ISSUE TITLE
Download bulk acquisition fails.

### ISSUE THREAD

**Issue by bw-0** [fireeye/HXTool#8]
HXTool version:4.5.1.2
HX version: 5.0.0.910952

```
Jun  4 15:24:00 hxtool.py: [2020-06-04 15:24:00,707] {app} {Thread-18712} ERROR - Exception on /api/v1/acquisition/bulk/download [GET]
Jun  4 15:24:00 hxtool.py: Traceback (most recent call last):
Jun  4 15:24:00 hxtool.py: File "/home/hxtool/hxtoolenv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
Jun  4 15:24:00 hxtool.py: response = self.full_dispatch_request()
Jun  4 15:24:00 hxtool.py: File "/home/hxtool/hxtoolenv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
Jun  4 15:24:00 hxtool.py: rv = self.handle_user_exception(e)
Jun  4 15:24:00 hxtool.py: File "/home/hxtool/hxtoolenv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
Jun  4 15:24:00 hxtool.py: reraise(exc_type, exc_value, tb)
Jun  4 15:24:00 hxtool.py: File "/home/hxtool/hxtoolenv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
Jun  4 15:24:00 hxtool.py: raise value
Jun  4 15:24:00 hxtool.py: File "/home/hxtool/hxtoolenv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
Jun  4 15:24:00 hxtool.py: rv = self.dispatch_request()
Jun  4 15:24:00 hxtool.py: File "/home/hxtool/hxtoolenv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
Jun  4 15:24:00 hxtool.py: return self.view_functions[rule.endpoint](**req.view_args)
Jun  4 15:24:00 hxtool.py: File "/home/hxtool/hxtoolenv/hxtool_util.py", line 51, in is_session_valid
Jun  4 15:24:00 hxtool.py: ret = f(*args, **kwargs)
Jun  4 15:24:00 hxtool.py: File "/home/hxtool/hxtoolenv/hxtool_api.py", line 546, in hxtool_api_acquisition_bulk_download
Jun  4 15:24:00 hxtool.py: bulk_acquisition_hosts[host['host']['_id']] = {'downloaded' : False, 'hostname' :  host['host']['hostname']}
Jun  4 15:24:00 hxtool.py: KeyError: 'hostname'
```
Thanks in advance, B

**Comment by B0fH** [comment]
Closing this now that 4.6 has been released.

**Comment by zdrouse** [comment]
I'm on 4.6 and using Chrome with no plugins.
While I don't receive any errors mentioned in this Issue, the download of the bulk acquisition doesn't provide a file.

The Download button becomes greyed out and the console log shows it was downloaded, but no file was received on my end.

`[2021-01-07 15:44:37,127] {hxtool_api} {Thread-141} INFO - ACTIVITY: msg='bulk acquisition action' action='download' id='79' hostset='1176' user='API' controller='CONTROLLER'`
